import{a as S,S as P,i as a}from"./assets/vendor-BkC4bTqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const q="https://pixabay.com/api/",B="54859534-8152a3885f48c1e8938887334";async function f(s,r=1){return(await S.get(q,{params:{key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more");function p(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const r=s.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p>Likes ${e.likes}</p>
        <p>Views ${e.views}</p>
        <p>Comments ${e.comments}</p>
        <p>Downloads ${e.downloads}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",r),E.refresh()}function M(){m.innerHTML=""}function L(){y.classList.add("visible")}function w(){y.classList.remove("visible")}const v=document.querySelector(".form"),$=v.elements["search-text"],O=document.querySelector(".load-more");let d="",n=1,u=0;const b=15;v.addEventListener("submit",async s=>{s.preventDefault();const r=$.value.trim();if(!r){a.error({title:"Error",message:"Please enter a search term."});return}d=r,n=1,M(),l(),L();try{const e=await f(d,n);if(u=e.totalHits,e.hits.length===0){a.error({title:"No result",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),u>b?p():a.info({message:"We're sorry, but you've reached the end of search results."})}catch{a.error({message:"Something went wrong. Please try again."})}finally{w()}});O.addEventListener("click",async()=>{n+=1,l(),L();try{const s=await f(d,n);g(s.hits),n*b>=u?(l(),a.info({message:"We're sorry, but you've reached the end of search results."})):p();const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}catch{a.error({message:"Something went wrong. Please try again."})}finally{w()}});
//# sourceMappingURL=index.js.map
